### ISSUE TITLE
new reading

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/sql-relational-databases-readme#1]
@jmburges

**Comment by AnnJohn** [comment]
Danny's comment - #2 

Managers column should be 'Manager ID' and Employees column should be 'Employee ID'

The reading and the images currently diverge.

**Comment by jmburges** [comment]
@SophieDeBenedetto when you want me to review something can you assign it to me? A bit easier to find on github searches.

**Comment by AnnJohn** [comment]
Yup, had already assigned it.

**Comment by jmburges** [comment]
comments left: https://github.com/learn-co-curriculum/edgar-codd-relational-databases/commit/58889c0ca43650bda02f3c8fe6f107e47f5d77dd

Fix that and :shipit: no need to have me do a second round

**Comment by SophieDeBenedetto** [comment]
fixed
